### ISSUE TITLE
The "normal" keybindings (like vs code) should support control-z for undo.

### ISSUE THREAD

**Issue by treeform** [Nimaoth/Absytree#8]
It looks like it uses Emacs control-y for undo?

**Comment by Nimaoth** [comment]
probably depends on what keyboard layout you're using. I think I set it up for the german layout where z and y are swapped. I'll have to see how to do that properly

**Comment by Nimaoth** [comment]
Changed it back so ctrl-z is undo, ctrl-y is redo.
